# Generated by Django 5.2.8 on 2025-11-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_user_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participants_id',
            new_name='participants',
        ),
    ]
