# Generated by Django 5.2.8 on 2025-11-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_participants_id_conversation_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
