# Generated by Django 5.2.8 on 2025-11-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_conversation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
