# Generated by Django 5.2.8 on 2025-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification_receiver_alter_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
