# Generated by Django 5.2.8 on 2025-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_rename_send_at_message_timestamp_messagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='is_read',
            field=models.BooleanField(),
        ),
    ]
