# Generated by Django 5.2.8 on 2025-12-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_messagehistory_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
