# Generated by Django 5.2.8 on 2025-12-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_messagehistory_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='edited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_messages_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
