# Generated by Django 5.2.8 on 2025-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_conversation_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
