apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-app
  template:
    metadata:
      labels:
        app: message-app
    spec:
      containers:
        - name: message-app
          image: keroojoseph/message_app:1.0
          ports:
            - containerPort: 8000