# Generated by Django 5.2.8 on 2025-11-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_conversation_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participants',
            new_name='participants_id',
        ),
    ]
