# Generated by Django 5.2.8 on 2025-11-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_rename_participants_conversation_participants_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participants_id',
            new_name='participants',
        ),
    ]
